### ISSUE TITLE
Set up result output

### ISSUE THREAD

**Issue by Armintron** [Armintron/CADET#1]
# Task List
- [ ] Color Coded Heat Map
- [x] GUI

# Branch: `heatmap`

**Comment by TBean18** [comment]
# Color Coded Heat Map

## Considerations
- What is the format of the output?

## Useful Links
- [TermColor](https://github.com/ikalnytskyi/termcolor)
  - System.out coloring library

**Comment by TBean18** [comment]
# GUI
![image](https://user-images.githubusercontent.com/49490724/159194470-44c2aa37-ebd3-4a5b-8110-dc22ae6a12a8.png)
![image](https://user-images.githubusercontent.com/49490724/159194479-ecf7fab7-b54a-486b-8da5-a82be5170e7d.png)

**Comment by Armintron** [comment]
Very cool! I think this is a very finalized look for what we need.

If you'd like, you can make a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) and use it as a pastebin for your branch progress, such as this 🤗
